<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Wallet extends Model
{
    const WALLET_IN = "in";
    const WALLET_OUT = "out";

    const walletTypeMap = [
        self::WALLET_IN => "收入",
        self::WALLET_OUT => "支出"
    ];

    public $table = "wallets";
    protected $guarded = [];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        // 监听模型创建事件，在写入数据库之前触发
        static::creating(function ($model) {
            // 如果模型的 pay_no 字段为空
            if (!$model->no) {
                // 调用 findAvailableNo 生成钱包流水号
                $model->no = static::findAvailableNo();
                // 如果生成失败，则终止创建订单
                if (!$model->no) {
                    return false;
                }
            }
        });
    }

    public function customer()
    {
        return $this->belongsTo(Customer::class,"customer_id");
    }

    public static function findAvailableNo()
    {
        // 钱包流水号前缀
        $prefix ="W".date('YmdHis');
        for ($i = 0; $i < 10; $i++) {
            // 随机生成 6 位的数字
            $no = $prefix.str_pad(random_int(0, 9999), 4, '0', STR_PAD_LEFT);
            // 判断是否已经存在
            if (!static::query()->where('no', $no)->exists()) {
                return $no;
            }
        }
        return false;
    }
}
